mods.MobStages.addStage("rangedEnemies", "minecraft:skeleton");
mods.MobStages.addStage("rangedEnemies", "minecraft:stray");
mods.MobStages.addStage("rangedEnemies", "primitivemobs:skeleton_warrior");
mods.MobStages.addStage("rangedEnemies", "mekanism:babyskeleton");
mods.MobStages.addStage("rangedEnemies", "iceandfire:if_cockatrice");
mods.MobStages.addStage("explosiveEnemies", "primitivemobs:festive_creeper");
mods.MobStages.addStage("explosiveEnemies", "primitivemobs:rocket_creeper");
mods.MobStages.addStage("explosiveEnemies", "minecraft:creeper");
/*mods.MobStages.addStage("raiders", "raiders:raider");
mods.MobStages.addStage("raiders", "raiders:brute");
mods.MobStages.addStage("raiders", "raiders:pyromaniac");
mods.MobStages.addStage("raiders", "raiders:tweaker");
mods.MobStages.addStage("raiders", "raiders:witch");
mods.MobStages.addStage("raiders", "raiders:ranger");*/
mods.MobStages.addStage("cyberEnemies", "cyberware:cyberzombie");
mods.MobStages.addStage("cyberEnemies", "rewired:cyberskeleton");